export const mockProducts = [
  {
    _id: "1",
    name: "Premium Wireless Headphones",
    description: "High-quality wireless headphones with noise cancellation",
    price: 21999,
    image: "/wireless-headphones.jpg",
    category: "electronics",
    stock: 50,
    rating: 4.5,
    reviews: [],
  },
  {
    _id: "2",
    name: "Luxury Silk Scarf",
    description: "Premium silk scarf with elegant patterns",
    price: 9899,
    image: "/silk-scarf.jpg",
    category: "fashion",
    stock: 30,
    rating: 4.8,
    reviews: [],
  },
  {
    _id: "3",
    name: "Modern Desk Lamp",
    description: "Contemporary desk lamp with adjustable brightness",
    price: 16499,
    image: "/desk-lamp.jpg",
    category: "home",
    stock: 25,
    rating: 4.3,
    reviews: [],
  },
  {
    _id: "4",
    name: "Organic Face Serum",
    description: "Natural organic face serum with vitamins",
    price: 6599,
    image: "/face-serum.jpg",
    category: "beauty",
    stock: 100,
    rating: 4.6,
    reviews: [],
  },
  {
    _id: "5",
    name: "Smart Watch Pro",
    description: "Advanced smartwatch with health tracking",
    price: 32999,
    image: "/modern-smartwatch.png",
    category: "electronics",
    stock: 40,
    rating: 4.4,
    reviews: [],
  },
  {
    _id: "6",
    name: "Cashmere Sweater",
    description: "Premium cashmere sweater in neutral tones",
    price: 19799,
    image: "/cashmere-sweater.jpg",
    category: "fashion",
    stock: 20,
    rating: 4.7,
    reviews: [],
  },
  {
    _id: "7",
    name: "Marble Coffee Table",
    description: "Elegant marble coffee table with metal base",
    price: 43999,
    image: "/coffee-table.jpg",
    category: "home",
    stock: 15,
    rating: 4.5,
    reviews: [],
  },
  {
    _id: "8",
    name: "Anti-Aging Cream",
    description: "Premium anti-aging cream with retinol",
    price: 8799,
    image: "/anti-aging-cream.jpg",
    category: "beauty",
    stock: 80,
    rating: 4.6,
    reviews: [],
  },
]
