export const mockPromoCodes = [
  {
    _id: "1",
    code: "WELCOME20",
    discount: 20,
    discountType: "percentage" as const,
    expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    usedCount: 245,
    maxUses: 1000,
    minOrderAmount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "2",
    code: "SUMMER50",
    discount: 50,
    discountType: "fixed" as const,
    expiresAt: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
    usedCount: 89,
    maxUses: 500,
    minOrderAmount: 100,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "3",
    code: "VIP30",
    discount: 30,
    discountType: "percentage" as const,
    expiresAt: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
    usedCount: 156,
    maxUses: 300,
    minOrderAmount: 200,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockFlashSales = [
  {
    _id: "1",
    name: "Electronics Weekend Sale",
    productIds: ["1", "5"],
    discount: 25,
    startTime: new Date(Date.now() - 2 * 60 * 60 * 1000),
    endTime: new Date(Date.now() + 22 * 60 * 60 * 1000),
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "2",
    name: "Fashion Flash Deal",
    productIds: ["2", "6"],
    discount: 35,
    startTime: new Date(Date.now() + 5 * 60 * 60 * 1000),
    endTime: new Date(Date.now() + 8 * 60 * 60 * 1000),
    active: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "3",
    name: "Home Essentials Flash",
    productIds: ["3", "7"],
    discount: 20,
    startTime: new Date(Date.now() - 5 * 60 * 60 * 1000),
    endTime: new Date(Date.now() + 19 * 60 * 60 * 1000),
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
