export const mockProducts = [
  // Gents Products
  {
    _id: "1",
    name: "Premium Wireless Headphones",
    description: "High-quality wireless headphones with noise cancellation",
    price: 21999,
    image: "/wireless-headphones.jpg",
    category: "electronics",
    gender: "gents",
    stock: 50,
    rating: 4.5,
    reviews: [],
    isFlashSale: false,
    discount: 0,
  },
  {
    _id: "2",
    name: "Men's Formal Shirt",
    description: "Premium cotton formal shirt for professional look",
    price: 3499,
    image: "/mens-formal-shirt.jpg",
    category: "fashion",
    gender: "gents",
    stock: 40,
    rating: 4.6,
    reviews: [],
    isFlashSale: true,
    discount: 20,
  },
  {
    _id: "3",
    name: "Smart Watch Pro",
    description: "Advanced smartwatch with health tracking",
    price: 32999,
    image: "/modern-smartwatch.png",
    category: "electronics",
    gender: "gents",
    stock: 40,
    rating: 4.4,
    reviews: [],
    isFlashSale: false,
    discount: 0,
  },
  {
    _id: "4",
    name: "Men's Casual Sneakers",
    description: "Comfortable casual sneakers for everyday wear",
    price: 5499,
    image: "/mens-sneakers.jpg",
    category: "fashion",
    gender: "gents",
    stock: 35,
    rating: 4.7,
    reviews: [],
    isFlashSale: true,
    discount: 15,
  },
  {
    _id: "5",
    name: "Leather Wallet",
    description: "Genuine leather wallet with multiple card slots",
    price: 2199,
    image: "/leather-wallet.jpg",
    category: "accessories",
    gender: "gents",
    stock: 60,
    rating: 4.8,
    reviews: [],
    isFlashSale: false,
    discount: 0,
  },
  {
    _id: "11",
    name: "Men's Denim Jeans",
    description: "Classic fit denim jeans with premium quality fabric",
    price: 4999,
    image: "/mens-jeans.jpg",
    category: "fashion",
    gender: "gents",
    stock: 50,
    rating: 4.6,
    reviews: [],
    isFlashSale: false,
    discount: 0,
  },
  {
    _id: "12",
    name: "Sports Running Shoes",
    description: "Lightweight running shoes with excellent grip",
    price: 6999,
    image: "/running-shoes.jpg",
    category: "fashion",
    gender: "gents",
    stock: 40,
    rating: 4.8,
    reviews: [],
    isFlashSale: true,
    discount: 25,
  },
  {
    _id: "13",
    name: "Men's Polo T-Shirt",
    description: "Comfortable polo t-shirt for casual wear",
    price: 1999,
    image: "/polo-tshirt.jpg",
    category: "fashion",
    gender: "gents",
    stock: 60,
    rating: 4.5,
    reviews: [],
    isFlashSale: false,
    discount: 0,
  },
  {
    _id: "14",
    name: "Leather Belt",
    description: "Genuine leather belt with classic buckle",
    price: 1499,
    image: "/leather-belt.jpg",
    category: "accessories",
    gender: "gents",
    stock: 70,
    rating: 4.7,
    reviews: [],
    isFlashSale: true,
    discount: 10,
  },
  {
    _id: "15",
    name: "Men's Sunglasses",
    description: "UV protection sunglasses with stylish design",
    price: 2999,
    image: "/mens-sunglasses.jpg",
    category: "accessories",
    gender: "gents",
    stock: 45,
    rating: 4.4,
    reviews: [],
    isFlashSale: false,
    discount: 0,
  },
  {
    _id: "16",
    name: "Men's Winter Jacket",
    description: "Warm winter jacket with water-resistant fabric",
    price: 8999,
    image: "/winter-jacket.jpg",
    category: "fashion",
    gender: "gents",
    stock: 30,
    rating: 4.9,
    reviews: [],
    isFlashSale: true,
    discount: 20,
  },
  {
    _id: "17",
    name: "Sports Watch",
    description: "Digital sports watch with multiple features",
    price: 3999,
    image: "/sports-watch.jpg",
    category: "accessories",
    gender: "gents",
    stock: 35,
    rating: 4.6,
    reviews: [],
    isFlashSale: false,
    discount: 0,
  },
  {
    _id: "18",
    name: "Men's Backpack",
    description: "Durable backpack with laptop compartment",
    price: 4499,
    image: "/mens-backpack.jpg",
    category: "accessories",
    gender: "gents",
    stock: 40,
    rating: 4.7,
    reviews: [],
    isFlashSale: false,
    discount: 0,
  },

  // Ladies Products
  {
    _id: "6",
    name: "Luxury Silk Scarf",
    description: "Premium silk scarf with elegant patterns",
    price: 9899,
    image: "/silk-scarf.jpg",
    category: "fashion",
    gender: "ladies",
    stock: 30,
    rating: 4.8,
    reviews: [],
    isFlashSale: false,
    discount: 0,
  },
  {
    _id: "7",
    name: "Organic Face Serum",
    description: "Natural organic face serum with vitamins",
    price: 6599,
    image: "/face-serum.jpg",
    category: "beauty",
    gender: "ladies",
    stock: 100,
    rating: 4.6,
    reviews: [],
    isFlashSale: true,
    discount: 25,
  },
  {
    _id: "8",
    name: "Designer Handbag",
    description: "Elegant designer handbag with premium finish",
    price: 15999,
    image: "/designer-handbag.jpg",
    category: "fashion",
    gender: "ladies",
    stock: 25,
    rating: 4.9,
    reviews: [],
    isFlashSale: false,
    discount: 0,
  },
  {
    _id: "9",
    name: "Anti-Aging Cream",
    description: "Premium anti-aging cream with retinol",
    price: 8799,
    image: "/anti-aging-cream.jpg",
    category: "beauty",
    gender: "ladies",
    stock: 80,
    rating: 4.6,
    reviews: [],
    isFlashSale: false,
    discount: 0,
  },
  {
    _id: "10",
    name: "Ethnic Kurti",
    description: "Beautiful ethnic kurti with traditional embroidery",
    price: 4299,
    image: "/ethnic-kurti.jpg",
    category: "fashion",
    gender: "ladies",
    stock: 45,
    rating: 4.7,
    reviews: [],
    isFlashSale: true,
    discount: 30,
  },
  {
    _id: "19",
    name: "Women's Saree",
    description: "Traditional saree with beautiful design",
    price: 7999,
    image: "/womens-saree.jpg",
    category: "fashion",
    gender: "ladies",
    stock: 35,
    rating: 4.8,
    reviews: [],
    isFlashSale: true,
    discount: 15,
  },
  {
    _id: "20",
    name: "Ladies Sandals",
    description: "Comfortable sandals with elegant design",
    price: 3499,
    image: "/ladies-sandals.jpg",
    category: "fashion",
    gender: "ladies",
    stock: 50,
    rating: 4.6,
    reviews: [],
    isFlashSale: false,
    discount: 0,
  },
  {
    _id: "21",
    name: "Women's Jewelry Set",
    description: "Elegant jewelry set with necklace and earrings",
    price: 5999,
    image: "/jewelry-set.jpg",
    category: "accessories",
    gender: "ladies",
    stock: 40,
    rating: 4.9,
    reviews: [],
    isFlashSale: true,
    discount: 30,
  },
  {
    _id: "22",
    name: "Ladies Watch",
    description: "Stylish watch with leather strap",
    price: 6499,
    image: "/ladies-watch.jpg",
    category: "accessories",
    gender: "ladies",
    stock: 35,
    rating: 4.7,
    reviews: [],
    isFlashSale: false,
    discount: 0,
  },
  {
    _id: "23",
    name: "Makeup Kit",
    description: "Complete makeup kit with essential items",
    price: 9999,
    image: "/makeup-kit.jpg",
    category: "beauty",
    gender: "ladies",
    stock: 30,
    rating: 4.8,
    reviews: [],
    isFlashSale: true,
    discount: 20,
  },
  {
    _id: "24",
    name: "Ladies Perfume",
    description: "Long-lasting perfume with floral fragrance",
    price: 4999,
    image: "/ladies-perfume.jpg",
    category: "beauty",
    gender: "ladies",
    stock: 60,
    rating: 4.6,
    reviews: [],
    isFlashSale: false,
    discount: 0,
  },
  {
    _id: "25",
    name: "Women's Salwar Kameez",
    description: "Elegant salwar kameez with embroidery work",
    price: 5499,
    image: "/salwar-kameez.jpg",
    category: "fashion",
    gender: "ladies",
    stock: 40,
    rating: 4.7,
    reviews: [],
    isFlashSale: true,
    discount: 25,
  },
  {
    _id: "26",
    name: "Ladies Handbag",
    description: "Stylish handbag with multiple compartments",
    price: 4299,
    image: "/ladies-handbag.jpg",
    category: "accessories",
    gender: "ladies",
    stock: 45,
    rating: 4.5,
    reviews: [],
    isFlashSale: false,
    discount: 0,
  },
  {
    _id: "27",
    name: "Hair Care Set",
    description: "Complete hair care set with shampoo and conditioner",
    price: 3999,
    image: "/hair-care-set.jpg",
    category: "beauty",
    gender: "ladies",
    stock: 55,
    rating: 4.6,
    reviews: [],
    isFlashSale: false,
    discount: 0,
  },
  {
    _id: "28",
    name: "Women's Sunglasses",
    description: "Fashionable sunglasses with UV protection",
    price: 2799,
    image: "/womens-sunglasses.jpg",
    category: "accessories",
    gender: "ladies",
    stock: 50,
    rating: 4.4,
    reviews: [],
    isFlashSale: true,
    discount: 15,
  },

  // Home & Others
  {
    _id: "29",
    name: "Modern Desk Lamp",
    description: "Contemporary desk lamp with adjustable brightness",
    price: 16499,
    image: "/desk-lamp.jpg",
    category: "home",
    gender: "unisex",
    stock: 25,
    rating: 4.3,
    reviews: [],
    isFlashSale: false,
    discount: 0,
  },
  {
    _id: "30",
    name: "Marble Coffee Table",
    description: "Elegant marble coffee table with metal base",
    price: 43999,
    image: "/coffee-table.jpg",
    category: "home",
    gender: "unisex",
    stock: 15,
    rating: 4.5,
    reviews: [],
    isFlashSale: false,
    discount: 0,
  },
]
